package com.kukri.moviecatalog.model;

import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import javax.persistence.*;

/**
 * Represents a Director entity in the movie catalog system.
 * Each Director has a unique ID and a name.
 *
 * This class is mapped to a database table via JPA annotations.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Director {

    /**
     * The unique identifier for the director.
     * It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full name of the director.
     */
    private String name;

    // Lombok @Data generates getters, setters, equals, hashCode, and toString
}